// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knkfrpppcszodzehalkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtua2ZycHBwY3N6b2R6ZWhhbGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1Mzk5NDUsImV4cCI6MjA2MzExNTk0NX0.AlyPYOau8d7uzBTpcME_XgFzL2OH_PUxsVbySrmT3Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);